#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Conversion AutoDock4 to elment
#

autodock4_atom_types_elements = {
    'H':   'H',
    'HD':  'H',
    'HS':  'H',
    'C':   'C',
    'A':   'C',
    'N':   'N',
    'NA':  'N',
    'NS':  'N',
    'OA':  'O',
    'OS':  'O',
    'F':   'F',
    'Mg':  'Mg',
    'MG':  'Mg',
    'P':   'P',
    'SA':  'S',
    'S':   'S',
    'Cl':  'Cl',
    'CL':  'Cl',
    'Ca':  'Ca',
    'CA':  'Ca',
    'Mn':  'Mn',
    'MN':  'Mn',
    'Fe':  'Fe',
    'FE':  'Fe',
    'Zn':  'Zn',
    'ZN':  'Zn',
    'Br':  'Br',
    'BR':  'Br',
    'I':   'I',
    'Si':  'Si',
    'At':  'At',
    'G0':  'C',
    'G1':  'C',
    'G2':  'C',
    'G3':  'C',
    'CG0': 'C',
    'CG1': 'C',
    'CG2': 'C',
    'CG3': 'C',
    'W':   'O',
    'S4':  'S',
    'A3':  'C',
    'A2':  'C',
    'C3':  'C',
    'C2':  'C',
    'C1':  'C',
    'H5':  'H',
    'O5':  'O',
    'F2':  'F',
    'N2':  'N',
    'N1':  'N'
}
